// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExperienceKeyInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Title     string `json:"title"`
	Company   string `json:"company"`
}
