// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ContactInfo struct {
	Email    string  `json:"email"`
	LinkedIn *string `json:"linkedIn"`
	Github   *string `json:"github"`
}

type Experience struct {
	StartDate        *string   `json:"start_date"`
	EndDate          *string   `json:"end_date"`
	Title            *string   `json:"title"`
	Company          *string   `json:"company"`
	Responsibilities []*string `json:"responsibilities"`
}

type ExperienceInput struct {
	StartDate        *string   `json:"start_date"`
	EndDate          *string   `json:"end_date"`
	Title            string    `json:"title"`
	Company          string    `json:"company"`
	Responsibilities []*string `json:"responsibilities"`
}

type GoSkills struct {
	Frameworks  []*string `json:"frameworks"`
	Paradigms   []*string `json:"paradigms"`
	AwsServices []*string `json:"aws_services"`
	Misc        []*string `json:"misc"`
}

type JSSkills struct {
	Frameworks  []*string `json:"frameworks"`
	Paradigms   []*string `json:"paradigms"`
	AwsServices []*string `json:"aws_services"`
	Misc        []*string `json:"misc"`
}

type Project struct {
	Name        string  `json:"name"`
	SourceCode  *string `json:"source_code"`
	DemoLink    *string `json:"demo_link"`
	Description *string `json:"description"`
}

type PythonSkills struct {
	Frameworks []*string `json:"frameworks"`
	Misc       []*string `json:"misc"`
}

type Skills struct {
	Js     *JSSkills     `json:"JS"`
	Go     *GoSkills     `json:"Go"`
	Python *PythonSkills `json:"Python"`
}

type UpdateMe struct {
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Title     *string `json:"title"`
	Location  *string `json:"location"`
}
